name: Tests

on: 
  push:
    tags:
      - 'test*'

jobs:
  tests:
    # https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        release: true
        update: true
        install: base-devel git mingw-w64-x86_64-toolchain mingw-w64-x86_64-qt5-static
        path-type: minimal
    - uses: actions/checkout@v2
    - name: Get Tag version
      id: get_version
      shell: bash
      run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"
    - name: Write CryToKey from Secrets to Headers files
      id: crytokey
      env:
        CRYTOKEY: ${{ secrets.CRYTOKEY }}
      run: |
        sed -i -r "s/crytokey = ([0-9]+)/crytokey = ${CRYTOKEY}/" configuration.h mainwindow.h
    - name: Build Test x64 release
      id: build_test
      run: |
        # Actualizar Qt install bins 
        PATH=/mingw64/qt5-static/bin/:$PATH
        qmake TestPicta-dl_GUI.pro -spec win32-g++
        # GitHub runner dont execute (Tests) .exe?
        # make check
        make -j 4 release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: picta-dl-gui_test
        body: "[Tests] Picta Downloader GUI ${{ steps.get_version.outputs.VERSION }}"
        draft: false
        prerelease: false
    - name: Upload Executable Picta-dl_GUI_Test.exe
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/Picta-dl_GUI_Test.exe
        asset_name: Picta-dl_GUI_Test.exe
        asset_content_type: application/octet-stream
